USE whoismikedion;

INSERT INTO skills (skill_id, canonical_name, category, proficiency, synonyms, notes) VALUES
('product-strategy', 'Product Strategy', 'pm_competency', 'expert', '["strategic planning", "product planning", "strategic thinking"]', NULL),
('stakeholder-management', 'Stakeholder Management', 'pm_competency', 'expert', '["client management", "relationship management", "stakeholder communication"]', NULL),
('user-research', 'User Research', 'pm_competency', 'expert', '["discovery", "user interviews", "customer research"]', NULL),
('requirements-translation', 'Requirements Translation', 'pm_competency', 'expert', '["requirements extraction", "technical translation", "requirements engineering"]', NULL),
('roadmap-planning', 'Roadmap Planning', 'pm_competency', 'proficient', '["product planning", "strategic planning", "feature prioritization"]', NULL),
('product-vision', 'Product Vision', 'pm_competency', 'expert', '["vision setting", "product direction", "strategic vision"]', NULL),
('0-to-1-product-development', '0-to-1 Product Development', 'pm_competency', 'expert', '["new product development", "product creation", "building from scratch"]', NULL),
('feature-prioritization', 'Feature Prioritization', 'pm_competency', 'expert', '["priority setting", "backlog management", "ruthless prioritization"]', NULL),
('go-to-market-strategy', 'Go-to-Market Strategy', 'pm_competency', 'proficient', '["GTM strategy", "market entry", "launch planning"]', NULL),
('product-marketing', 'Product Marketing', 'pm_competency', 'proficient', '["marketing strategy", "positioning", "messaging"]', NULL),
('value-proposition-development', 'Value Proposition Development', 'pm_competency', 'expert', '["value creation", "positioning", "messaging strategy"]', NULL),
('product-operations', 'Product Operations', 'pm_competency', 'expert', '["product ops", "operational excellence", "process design"]', NULL),
('metrics-and-analytics', 'Metrics and Analytics', 'pm_competency', 'proficient', '["data analysis", "KPI tracking", "performance measurement"]', NULL),
('project-management', 'Project Management', 'pm_competency', 'expert', '["program management", "delivery management", "execution"]', NULL),
('cross-functional-coordination', 'Cross-Functional Coordination', 'pm_competency', 'expert', '["team coordination", "collaboration", "stakeholder alignment"]', NULL);

INSERT INTO skills (skill_id, canonical_name, category, proficiency, synonyms, notes) VALUES
('ai-ml-integration', 'AI/ML Integration', 'technical_skill', 'expert', '["artificial intelligence", "machine learning", "LLM integration"]', NULL),
('vector-databases', 'Vector Databases', 'technical_skill', 'proficient', '["embeddings", "semantic search", "similarity search", "Redis vector"]', NULL),
('ai-workflow-design', 'AI Workflow Design', 'technical_skill', 'expert', '["LLM workflow", "AI process design", "automation workflows"]', NULL),
('system-architecture', 'System Architecture', 'technical_skill', 'expert', '["software architecture", "system design", "architectural patterns"]', NULL),
('api-design', 'API Design', 'technical_skill', 'expert', '["REST API", "API architecture", "endpoint design", "AJAX"]', NULL),
('database-design', 'Database Design', 'technical_skill', 'expert', '["data modeling", "schema design", "database architecture"]', NULL),
('wordpress-development', 'WordPress Development', 'technical_skill', 'expert', '["WP development", "CMS development", "custom theme development"]', NULL),
('headless-cms', 'Headless CMS', 'technical_skill', 'expert', '["decoupled CMS", "API-first CMS", "JAMstack"]', NULL),
('static-site-generation', 'Static Site Generation', 'technical_skill', 'expert', '["SSG", "JAMstack", "static sites"]', NULL),
('performance-optimization', 'Performance Optimization', 'technical_skill', 'expert', '["speed optimization", "web performance", "load time optimization"]', NULL),
('caching-strategies', 'Caching Strategies', 'technical_skill', 'expert', '["server caching", "edge caching", "cache optimization"]', NULL),
('frontend-development', 'Frontend Development', 'technical_skill', 'expert', '["UI development", "JavaScript", "web development"]', 'Strong foundation in frontend concepts and patterns (component architecture, state management, interactive UIs). Not framework-specific (doesn''t write React/Vue/Angular day-to-day) but understands what frontend frameworks do and why. Value is in understanding feasibility and patterns, not writing framework code.'),
('component-architecture', 'Component Architecture', 'technical_skill', 'expert', '["component design", "atomic design", "design systems"]', NULL),
('geolocation-technology', 'Geolocation Technology', 'technical_skill', 'proficient', '["GPS", "geofencing", "location-based services"]', NULL),
('iot-integration', 'IoT Integration', 'technical_skill', 'proficient', '["Internet of Things", "smart home integration", "device integration"]', NULL),
('debugging-methodology', 'Debugging Methodology', 'technical_skill', 'expert', '["troubleshooting", "problem diagnosis", "systematic debugging"]', NULL),
('content-moderation', 'Content Moderation', 'technical_skill', 'proficient', '["ML moderation", "automated moderation", "safety systems"]', NULL),
('recommendation-algorithms', 'Recommendation Algorithms', 'technical_skill', 'proficient', '["recommendation engines", "personalization", "algorithmic recommendations"]', NULL),
('multi-tenant-architecture', 'Multi-Tenant Architecture', 'technical_skill', 'expert', '["SaaS architecture", "multi-tenancy", "tenant isolation"]', NULL),
('seo-optimization', 'SEO Optimization', 'technical_skill', 'expert', '["search engine optimization", "keyword research", "organic search"]', NULL),
('feature-flags', 'Feature Flags', 'technical_skill', 'expert', '["feature toggles", "feature management", "progressive delivery"]', NULL),
('paper-js', 'Paper.js', 'technical_skill', 'proficient', '["vector graphics", "canvas manipulation", "interactive graphics"]', NULL),
('rapid-prototyping', 'Rapid Prototyping', 'technical_skill', 'expert', '["quick iteration", "fast development", "MVP building"]', NULL),
('sql', 'SQL', 'technical_skill', 'proficient', '["MySQL", "database queries", "data querying", "SQL queries"]', NULL),
('php-development', 'PHP Development', 'technical_skill', 'expert', '["PHP programming", "server-side development", "backend development"]', NULL);

INSERT INTO skills (skill_id, canonical_name, category, proficiency, synonyms, notes) VALUES
('systems-thinking', 'Systems Thinking', 'soft_skill', 'expert', '["holistic thinking", "system design", "pattern recognition"]', NULL),
('problem-solving', 'Problem Solving', 'soft_skill', 'expert', '["analytical thinking", "critical thinking", "solution design"]', NULL),
('emotional-intelligence', 'Emotional Intelligence', 'soft_skill', 'expert', '["EQ", "empathy", "self-awareness"]', NULL),
('emotional-regulation', 'Emotional Regulation', 'soft_skill', 'expert', '["composure", "stress management", "calm under pressure"]', NULL),
('crisis-management', 'Crisis Management', 'soft_skill', 'expert', '["emergency response", "pressure handling", "incident management"]', NULL),
('communication', 'Communication', 'soft_skill', 'expert', '["verbal communication", "written communication", "presentation"]', NULL),
('empathy', 'Empathy', 'soft_skill', 'expert', '["user empathy", "understanding others", "compassion"]', NULL),
('pattern-recognition', 'Pattern Recognition', 'soft_skill', 'expert', '["trend identification", "insight discovery", "analytical thinking"]', NULL),
('adaptability', 'Adaptability', 'soft_skill', 'expert', '["flexibility", "agility", "pivoting"]', NULL),
('resilience', 'Resilience', 'soft_skill', 'expert', '["perseverance", "grit", "persistence"]', NULL),
('creativity', 'Creativity', 'soft_skill', 'expert', '["innovation", "creative thinking", "ideation"]', NULL),
('process-innovation', 'Process Innovation', 'soft_skill', 'expert', '["process improvement", "workflow design", "operational innovation"]', NULL),
('teaching-mentorship', 'Teaching & Mentorship', 'soft_skill', 'expert', '["coaching", "training", "knowledge transfer"]', NULL),
('attention-to-detail', 'Attention to Detail', 'soft_skill', 'expert', '["detail-oriented", "precision", "thoroughness"]', NULL),
('resourcefulness', 'Resourcefulness', 'soft_skill', 'expert', '["ingenuity", "creative problem-solving", "making do with constraints"]', NULL),
('time-management', 'Time Management', 'soft_skill', 'expert', '["prioritization", "deadline management", "efficiency"]', NULL),
('continuous-learning', 'Continuous Learning', 'soft_skill', 'expert', '["lifelong learning", "self-education", "skill development"]', NULL),
('boundary-setting-emotional', 'Boundary Setting (Emotional/Professional)', 'soft_skill', 'proficient', '["emotional boundaries", "professional composure", "stress management"]', 'Strong at setting boundaries around emotional pressure (3-5 second pause technique), maintaining composure with difficult stakeholders, and not taking on others'' stress. Holds technical boundaries well (standing firm on quality decisions).'),
('boundary-setting-financial', 'Boundary Setting (Financial/Scope)', 'soft_skill', 'developing', '["scope management", "financial boundaries", "self-advocacy"]', 'Struggles with in-person scope/financial boundaries when self is beneficiary (loses 4-20 hours per project to scope creep, undercharges significantly). Strong via email (time to process). Works well with external authority (representing employer). Root cause: religious programming about self-sacrifice, difficulty advocating for own needs. Active mitigation: ''let me email you later'' script, Claude accountability system.'),
('professional-grace', 'Professional Grace', 'soft_skill', 'expert', '["diplomacy", "tact", "professionalism"]', NULL),
('team-collaboration', 'Team Collaboration', 'soft_skill', 'developing', '["collaborative work", "teamwork", "pair programming", "code review"]', 'Limited formal team collaboration experience - has always been technical lead or solo. Strong collaborative instincts (defers when appropriate, advocates respectfully), but lacks exposure to modern team practices like pair programming, formal code review culture, team git workflows.'),
('influence-without-authority', 'Influence Without Authority', 'soft_skill', 'proficient', '["lateral influence", "persuasion", "advocacy"]', 'Demonstrated ability to propose changes without positional authority (preventative maintenance tracker example). Frames proposals around others'' needs. Expects rejection gracefully. Limited exposure to collaborative decision-making as peer rather than leader.');

INSERT INTO skills (skill_id, canonical_name, category, proficiency, synonyms, notes) VALUES
('content-strategy', 'Content Strategy', 'domain_knowledge', 'expert', '["editorial strategy", "content planning", "content development"]', NULL),
('seo-strategy', 'SEO Strategy', 'domain_knowledge', 'expert', '["search strategy", "organic growth", "keyword strategy"]', NULL),
('ecommerce', 'E-Commerce', 'domain_knowledge', 'proficient', '["online retail", "digital commerce", "web stores"]', NULL),
('saas-platforms', 'SaaS Platforms', 'domain_knowledge', 'expert', '["software as a service", "platform development", "cloud platforms"]', NULL),
('social-platforms', 'Social Platforms', 'domain_knowledge', 'proficient', '["social media", "community platforms", "user-generated content"]', NULL),
('gaming-entertainment', 'Gaming & Entertainment', 'domain_knowledge', 'proficient', '["casual gaming", "puzzle games", "entertainment products"]', NULL),
('local-business-marketing', 'Local Business Marketing', 'domain_knowledge', 'expert', '["local SEO", "small business marketing", "regional marketing"]', NULL),
('b2b-marketing', 'B2B Marketing', 'domain_knowledge', 'proficient', '["business-to-business", "enterprise marketing", "wholesale marketing"]', NULL),
('demand-generation', 'Demand Generation', 'domain_knowledge', 'proficient', '["lead generation", "demand creation", "pull marketing"]', NULL),
('compliance-navigation', 'Compliance Navigation', 'domain_knowledge', 'proficient', '["regulatory compliance", "legal requirements", "industry regulations"]', NULL),
('user-experience-design', 'User Experience Design', 'domain_knowledge', 'expert', '["UX design", "experience design", "interaction design"]', NULL),
('user-psychology', 'User Psychology', 'domain_knowledge', 'expert', '["behavioral psychology", "user behavior", "cognitive psychology"]', NULL),
('design-systems', 'Design Systems', 'domain_knowledge', 'expert', '["component libraries", "design patterns", "UI systems"]', NULL),
('platform-engineering', 'Platform Engineering', 'domain_knowledge', 'expert', '["developer platforms", "infrastructure platforms", "platform development"]', NULL),
('marketing-automation', 'Marketing Automation', 'domain_knowledge', 'proficient', '["automated marketing", "marketing workflows", "campaign automation"]', NULL),
('conversion-optimization', 'Conversion Optimization', 'domain_knowledge', 'proficient', '["CRO", "funnel optimization", "conversion rate optimization"]', NULL),
('roi-optimization', 'ROI Optimization', 'domain_knowledge', 'expert', '["return on investment", "value creation", "business outcomes"]', NULL),
('constraint-driven-innovation', 'Constraint-Driven Innovation', 'domain_knowledge', 'expert', '["working with constraints", "creative constraints", "limitation as opportunity"]', NULL),
('technical-debt-management', 'Technical Debt Management', 'domain_knowledge', 'expert', '["code quality", "maintainability", "refactoring"]', NULL),
('live-operations', 'Live Operations', 'domain_knowledge', 'proficient', '["production support", "operational monitoring", "real-time fixes"]', NULL),
('legacy-system-management', 'Legacy System Management', 'domain_knowledge', 'proficient', '["legacy systems", "old system maintenance", "technical debt navigation"]', NULL);

UPDATE skills SET is_top_skill = TRUE WHERE skill_id IN (
    'product-strategy',
    'systems-thinking',
    'ai-ml-integration',
    'problem-solving',
    'wordpress-development',
    'frontend-development',
    'user-experience-design',
    'system-architecture'
);

